apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: py9hjbjck-dotnet-basic 
  janus-idp.io/tekton: py9hjbjck-dotnet-basic
  backstage.io/kubernetes-id: py9hjbjck-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: py9hjbjck-dotnet-basic
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml